name: 'Build Release Package'
description: 'Build a single package (python or cpp) for release'
inputs:
  package:
    description: 'Package type (python or cpp)'
    required: true
  version:
    description: 'Version string'
    required: true
  pypi_version:
    description: 'PyPI version string'
    required: true
  display_version:
    description: 'Display version string'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.14.0
      with:
        enable-cache: 'true'
        devbox-version: 0.16.0
     
    # - name: Build package
    #   shell: bash
    #   run: |
    #     if [ "${{ inputs.package }}" == "python" ]; then
    #       devbox run -- task release:package:python:${{ inputs.pypi_version }}
    #     else
    #       devbox run -- task release:package:cpp:${{ inputs.version }}
    #     fi
    
    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v7.0.0
    #   with:
    #     name: finance-proto-models-${{ inputs.package }}-${{ inputs.display_version }}
    #     path: |
    #       release/${{ inputs.package }}/*
    #     retention-days: 1