name: 'Setup Environment'
description: 'Checkout code and install devbox'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      shell: bash
    
    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.12.0
      shell: bash