version: '3'
includes:
  cpp: Taskfile.cpp.yml

tasks:

  validate:
    desc: Validate the protobuf definition and current buf config
    cmd: buf build

  lint:
    desc: Lint the protobuf definitions
    cmd: buf lint

  generate:
    desc: Generate the protobuf code
    cmd: buf generate

  check:breaking:for:
    desc: Check whether the current state has breaking changes against the remote state (git branch)
    vars:
      REMOTE: '{{.CLI_ARGS}}'
    cmd: buf breaking --against {{.REMOTE}}

  test:*:
    desc: Test generated releases for the provided target [python, cpp]
    vars:
      TARGET: '{{index .MATCH 0}}'
    preconditions:
      - sh: test -d $RELEASE_DIR/{{.TARGET}}
        msg: "Required directory release/'{{.TARGET}}' not found, call task release:package:{{.TARGET}} first"
    cmd: bash tests/{{.TARGET}}/test.sh