version: '3'

tasks:

  proto:list-files:
    desc: List all protobuf files in the src directory
    silent: true
    cmd: find $DEVBOX_PROJECT_ROOT/src -name "*.proto"
    
  proto:extract:namespace:
    desc: Extract the package namespace - printing it to stdout
    silent: true
    cmd: echo "$(grep -E "^package\s+\w+" $DEVBOX_PROJECT_ROOT/src/envelope.proto | sed 's/package\s*\([^;]*\);/\1/')"
  
  proto:build:*:
    desc: Build protobuf code for the provided target [python, cpp]
    silent: true
    vars:
      TARGET: '{{index .MATCH 0}}'
    deps:
      - clean:build:{{.TARGET}}
    cmds:
      - mkdir -p $BUILD_DIR/{{.TARGET}}
      - |
        files=$(task proto:list-files)
        for file in $files; do
          protoc -I $DEVBOX_PROJECT_ROOT/src --{{.TARGET}}_out=$BUILD_DIR/{{.TARGET}} $file
        done

  poetry:install:
    desc: Install dependencies
    cmd: poetry install

  poetry:build:*:
    desc: Build the protobuf python package
    silent: true
    deps:
      - task: proto:build:python
    vars:
      VERSION: '{{index .MATCH 0}}'

    cmds:
    - cp -r $RESOURCES_DIR/py/pyproject.toml $RESOURCES_DIR/py/README.md $BUILD_DIR/python/
    - mkdir -p $BUILD_DIR/python/finance_proto_models
    - |
      find "$BUILD_DIR/python" \
        ! -name "pyproject.toml" \
        ! -name "README.md" \
        ! -name "finance_proto_models" \
        -exec mv {} "$BUILD_DIR/python/finance_proto_models/" \;

    - poetry version {{.VERSION}} --directory $BUILD_DIR/python
    - poetry build --directory $BUILD_DIR/python

  clean:build:*:
    vars:
      TARGET: '{{index .MATCH 0}}'
    desc: Clean up previous build
    silent: true
    cmd: rm -rf $BUILD_DIR/{{.TARGET}} || true

  clean:release:*:
    vars:
      TARGET: '{{index .MATCH 0}}'
    desc: Clean up previous release
    silent: true
    cmd: rm -rf $RELEASE_DIR/{{.TARGET}} || true

  release:create-version-txt:*:*:
    vars:
      TARGET: '{{index .MATCH 0}}'
      VERSION: '{{index .MATCH 1}}'
    desc: Create a version.txt file with variables 0 -> target, 1 -> version
    silent: true
    cmd: |
      cat > $RELEASE_DIR/{{.TARGET}}/version.txt << EOF
      {{.VERSION}}
      $(git rev-parse HEAD)
      $(date -u +"%Y-%m-%dT%H:%M:%SZ")
      EOF

  release:package:cpp:*:
    desc: Build C++ package for release
    silent: true
    vars:
      PACKAGE_VERSION: '{{index .MATCH 0}}'
    deps:
      - clean:build:cpp > /dev/null
      - clean:release:cpp > /dev/null
      - proto:build:cpp > /dev/null
    cmds:
      - echo "Packaging release for version -> {{.PACKAGE_VERSION}}"

      # Create tmp folder for the package
      - mkdir -p $RELEASE_DIR/cpp

      # Create a version.txt
      - task release:create-version-txt:cpp:{{.PACKAGE_VERSION}}

      # Copy to release & create tarball
      - |
        cp -r $RESOURCES_DIR/cpp/* $BUILD_DIR/cpp/* $RELEASE_DIR/cpp
        tar -czf finance-proto-models-cpp.tar.gz -C $RELEASE_DIR/cpp .
        mv finance-proto-models-cpp.tar.gz $RELEASE_DIR/cpp
        rm -rf $RELEASE_DIR/cpp/finance-proto-models $RELEASE_DIR/cpp/version.txt $RELEASE_DIR/cpp/README.md
  
  release:package:python:*:
    desc: Build Python wheel for release
    silent: true
    vars:
      PACKAGE_VERSION: '{{index .MATCH 0}}'
    deps:
      - clean:build:python > /dev/null
      - clean:release:python > /dev/null
    cmds:
      - echo "Packaging release for version -> {{.PACKAGE_VERSION}}"

      # Create tmp folder for the package
      - mkdir -p $RELEASE_DIR/python

      # Create a version.txt
      - task release:create-version-txt:python:{{.PACKAGE_VERSION}}

      # Build the package
      - task poetry:build:{{.PACKAGE_VERSION}}
      - cp $BUILD_DIR/python/dist/* $RELEASE_DIR/python/

  release:package:all:*:
  
    desc: Build all packages for release
    silent: true
    vars:
      PACKAGE_VERSION: '{{index .MATCH 0}}'
    deps:
      - task: release:package:cpp:{{.PACKAGE_VERSION}}
      - task: release:package:py:{{.PACKAGE_VERSION}}

  test:*:
    desc: Test generated releases for the provided target [python, cpp]
    vars:
      TARGET: '{{index .MATCH 0}}'
    preconditions:
      - sh: test -d $RELEASE_DIR/{{.TARGET}}
        msg: "Required directory release/'{{.TARGET}}' not found, call task release:package:{{.TARGET}} first"
    cmd: bash tests/{{.TARGET}}/test.sh